import Colors from './Colors'

const template = [
  {
    key: 0,
    title: 'Ice cream is made with carrageenan LOREM IPSUM',
    description: '',
    moderator: [''],
    moderatorTitle: [''],
    speaker: [''],
    speakerTitle: [''],
    classImg: require('../assets/images/class1.png'),
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 1,
    title: 'Ice cream is made with carrageenan LOREM IPSUM',
    classImg: require('../assets/images/class2.png'),
    textColor: 'white',
    textColorCta: Colors.primaryColor,
    bgCta: Colors.class1,
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 2,
    title: 'Ice cream is made with carrageenan LOREM IPSUM',
    classImg: require('../assets/images/class3.png'),
    textColor: 'white',
    bgCta: Colors.class2,
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 3,
    title: 'Ice cream is made with carrageenan LOREM IPSUM',
    classImg: require('../assets/images/class4.png'),
    textColor: 'white',
    bgCta: Colors.class3,
    cta: 'Time: TBA',
    horizontal: true
  },
];

export const classesDay1 = [
  {
    key: 0,
    classBg: require('../assets/images/class4-bg.png'),
    title: 'Becoming Data Scientist: A New Sherlock of Digital Era',
    description: 'Saat ini data banyak terbentuk dan tersebar dimana mana. Saat kita membuka sosial media, memesan taksi online sampai pembelian tiket pesawat. Semuanya menghasilkan data, namun terpecah-pecah layaknya puzzle. Siapa yang dapat mendapatkan potongan puzzle yang tepat dan merangkainya dengan tepat akan dapat memecahkan masalah dan menjadi pemenang di era digital seperti beberapa Unicorn yang saat ini berhasil memecahkan masalah di masyrakat dan menghasilkan dampak besar. Siapa yang berperan dalam hal ini? Dialah Data Scientist layaknya Sherlock Holmes di era digital, mampu melakukan deduksi, sintesis dan analisis untuk memecahkan masalah dengan data',
    moderator: ['Hendra Saputra'],
    moderatorTitle: ['Business Manager to CMO Telkomsel'],
    speaker: ['Fajar Jaman', 'Fajar Muharandy'],
    speakerTitle: ['CEO Iykra', 'Solution Engineer at Cloudera'],
    classImg: require('../assets/images/class4.png'),
    textColor: 'white',
    bgCta: Colors.class3,
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 1,
    classBg: require('../assets/images/class3-bg.png'),
    title: 'Digital Marketing Complexity—Clarity of Objectives',
    description: 'Perkembangan teknologi mengubah cara konsumen mencari informasi, berinteraksi, dan membeli produk. Teknologi juga membantu perusahaan untuk mengenal, memahami, dan terhubung dengan konsumen. Di sesi ini kita akan belajar bagaimana Digital Marketing akan memaksimalkan cara perusahaan untuk kenal lebih dalam tentang konsumen serta tahu bagaimana caranya untuk bisa memberikan pengaruh supaya konsumen mau membeli produk dengan memanfaatkan teknologi digital yang ada di saat ini',
    moderator: ['Trivet Sembel'],
    moderatorTitle: ['Founder & CEO Proud Media Group'],
    speaker: ['Kemas M Fadhli', 'Rifqi Edrus'],
    speakerTitle: ['GM BrandComm at Telkomsel', 'Director Marketing at SOUL Electronics'],
    classImg: require('../assets/images/class3.png'),
    description: 'Perkembangan teknologi mengubah cara konsumen mencari informasi, berinteraksi, dan membeli produk. Teknologi juga membantu perusahaan untuk mengenal, memahami, dan terhubung dengan konsumen. Di sesi ini kita akan belajar bagaimana Digital Marketing akan memaksimalkan cara perusahaan untuk kenal lebih dalam tentang konsumen serta tahu bagaimana caranya untuk bisa memberikan pengaruh supaya konsumen mau membeli produk dengan memanfaatkan teknologi digital yang ada di saat ini',
    textColor: 'white',
    bgCta: Colors.class2,
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 2,
    classBg: require('../assets/images/class3-bg.png'),
    title: 'The Hustler for Your Ideas',
    description: 'Seringkali kita memiliki ide – ide inovatif yang brilian. Akan tetapi, terkadang untuk mewujudkannya kita butuh bantuan dari pihak lain. Oleh karena itu di sesi ini kita akan belajar bagaimana caranya agar kita bisa ‘menjual’ ide kita agar dapat dipahami dan dibeli oleh pihak – pihak yang dapat membantu mewujudkan inovasi kita.',
    moderator: ['Eko Seno Prianto'],
    moderatorTitle: ['GM Business Incubation at Telkomsel'],
    speaker: ['Dondi Hananto'],
    speakerTitle: ['Partner at Patamar Capital'],
    classImg: require('../assets/images/class3.png'),
    textColor: 'white',
    bgCta: Colors.class2,
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 3,
    classBg: require('../assets/images/class4-bg.png'),
    title: 'Living as a UX Specialist',
    description: 'Dalam sesi ini audien akan mengetahui apa yang dimaksud UI/UX dan fungsi UI/UX dalam mengembangkan suatu produk yang tepat sehingga sesuai dengan kebutuhan end user dan end user merasa nyaman serta berkesan dengan produk yang ditawarkan. Audien mengetahui pentingnya UI/UX ini di dalam perkembangan industry. Selain itu audien akan mengetahui peluang menjadi seorang UI/UX dan bisa mendeteksi apakah bisa menjadi seorang UI/UX dan bagaimana menjadi seorang UI dan UX yang handal.',
    moderator: ['Fri Rasyidi'],
    moderatorTitle: ['Senior Interaction Designer at Somia'],
    speaker: ['Borrys Hasian', 'Wendy Novianto'],
    speakerTitle: ['Director of DesignOps at Gojek', 'Managing Director at Aleph-Labs'],
    classImg: require('../assets/images/class4.png'),
    textColor: 'white',
    bgCta: Colors.class3,
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 4,
    classBg: require('../assets/images/class3-bg.png'),
    title: 'Digital Services for B2B Business',
    description: 'Menghadapi kondisi pasar yang semakin challenging, banyak perusahaan berusaha meningkatkan daya saingnya dengan semakin berfokus dalam menjawab kebutuhan konsumen. Customer centricity menjadi jargon yang kian nyaring terdengar, mengingatkan bahwa segala hal yang dilakukan perusahaan haruslah dengan tujuan menjawab kebutuhan pelanggan. Memberikan solusi terhadap permasalahan konsumen tidaklah mudah. Oleh karena itu, di sesi ini kita akan belajar lebih dalam tentang betapa pentingnya customer centricity dan bagaimana caranya bisa mem-provide solution yang bagi customer yang dapat meningkatkan nilai jual di pasaran.',
    moderator: ['Fachrul A Daulay'],
    moderatorTitle: ['Manager IOT Research and Marketing at Telkomsel'],
    speaker: ['Dharma Simorangkir'],
    speakerTitle: ['SVP Enterprise at Telkomsel'],
    classImg: require('../assets/images/class3.png'),
    textColor: 'white',
    bgCta: Colors.class2,
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 5,
    classBg: require('../assets/images/class2-bg.png'),
    title: 'Fintech—What\'s next?',
    description: 'Industri Fintech terus berubah dengan cepat. Banyak perusahaan mencoba bermain di bidang ini. Indonesia dengan demografinya yang masif menjadi salah satu pasar yang paling menarik. Tantangan dan peluang apa yang dimiliki perusahaan Fintech di Indonesia? Bagaimana mereka bisa beradaptasi untuk memenangkan pasar? Keterampilan apa yang dibutuhkan oleh industri?',
    moderator: ['Nazier Ariffin'],
    moderatorTitle: ['Head of Investment at Telkomsel Mitra Inovasi'],
    speaker: ['Edward Killian'],
    speakerTitle: ['CMO LinkAja'],
    classImg: require('../assets/images/class2.png'),
    textColor: 'white',
    bgCta: Colors.class3,
    cta: 'Time: TBA',
    horizontal: true
  },
];

export const classesDay2 = [
  {
    key: 7,
    classBg: require('../assets/images/class3-bg.png'),
    title: 'Caster Academy & Studio Gaming Showcase',
    description: 'Digital Product Sales Jawa Bali Team merilis Caster Academy dan Studio Gaming pertama di Indonesia. Sebuah karya dari tim Area Jawa Bali sebagai bentuk inovasi dan kontribusi terhadap business digital yang sedang diusung Telkomsel. Sesi Digital Gaming akan menampilkan live gaming, castering dan live streaming via MaxStream.',
    moderator: [],
    moderatorTitle: [],
    speaker: ['Digital Product Sales Jawa Bali Team'],
    speakerTitle: ['Telkomsel'],
    classImg: require('../assets/images/class3.png'),
    textColor: 'white',
    bgCta: Colors.class2,
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 8,
    classBg: require('../assets/images/class2-bg.png'),
    title: 'The Future—Ready Workforce',
    description: 'Ketika maraknya teknologi digital dan hal baru yang terus mendisrupsi kondisi saat ini, kemampuan dan kemauan kita untuk dapat cepat beradaptasi menjadi suatu tuntutan dan keharusan. Sesi ini ”The Future-ready Workforce” akan memberikan jawaban kepada kita bagaimana mempersiapkan diri untuk masa depan, terutama dalam menghadapi Revolusi Industri 4.0.. Sesi ini akan menghadirkan expert career and talent management yaitu Ken Ratri Iswari, Founder & CEO Geekhunter dan Andi Kristianto, CEO Telkomsel Mitra Inovasi, dan akan dimoderatori oleh Vany Yulviany, GM Talent & Career Management and HC Revamp Telkomsel.',
    moderator: ['Vany Yulviany'],
    moderatorTitle: ['GM Talent and Career Management at Telkomsel'],
    speaker: ['Andi Kristianto', 'Ken Ratri Iswari'],
    speakerTitle: ['CEO Telkomsel Mitra Inovasi', 'Founder & CEO Geekhunter'],
    classImg: require('../assets/images/class2.png'),
    textColor: 'white',
    textColorCta: Colors.primaryColor,
    bgCta: Colors.class1,
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 6,
    classBg: require('../assets/images/class4-bg.png'),
    title: 'Beating the Odds with Data Science',
    description: 'Jargon ‘Data is the New Oil’ semakin nyata relevansinya dengan bisnis Digital Telco dan itu berhubungan erat dengan Data Science. Lalu apa itu Data Science? Bagaimana bisnis Data Science dalam skala global? Bagaimana implementasi Data Science dalam industri bisnis Telco? Mengapa talent Data Science saat ini masih langka? Simak jawabannya pada sesi ini yang akan menghadirkan Expert Data Science Global yaitu Wojtek Krok dari QuantumBlack – South East Asia.',
    moderator: [],
    moderatorTitle: [],
    speaker: ['Wojtek Krok'],
    speakerTitle: ['Leader of Quantum Black South-East Asia'],
    classImg: require('../assets/images/class4.png'),
    textColor: 'white',
    bgCta: Colors.class3,
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 9,
    classBg: require('../assets/images/class1-bg.png'),
    title: 'We the People 4.0',
    description: 'Perubahan di dunia industri terjadi dengan begitu cepat dan berbahaya bagi setiap pihak di dalamnya. Menghadapi perubahan di era industri, kita tidak bisa berpuas dengan keadaan yang begitu – begitu saja. Oleh karena itu, kita akan mendengar tentang betapa pentingnya untuk berubah dan apa yang harus kita lakukan agar bisa shifting dan menjadi The People 4.0',
    moderator: ['Irzan Raditya'],
    moderatorTitle: ['CEO & Co-Founder Kata.ai'],
    speaker: ['Noni Purnomo', 'Alamanda Shantika'],
    speakerTitle: ['CEO Bluebird', 'Founder & CEO Binar Academy'],
    classImg: require('../assets/images/class1.png'),
    cta: 'Time: TBA',
    horizontal: true
  },
  {
    key: 10,
    classBg: require('../assets/images/class1-bg.png'),
    title: 'Fast Forward to be Future People—Leading or left behind',
    description: 'Masa depan akan sangat berbeda dari yang kita lihat sekarang. 800 juta pekerja akan tergantikan oleh mesin. Teknologi tingkat seperti Artificial Intelligence, Robotika dan Machine Learning akan menjadi kebutuhan primer seperti hal nya listrik dan telepon. Di masa depan akan bermunculan pekerjaan yang kini bahkan belum muncul. Kemajuan teknologi memaksa kita semua untuk mampu mengejar jaman. Kendalilan teknologi sebelum teknologi mengendalikan kita. Untuk mampu mengikuti perkembangan teknologi kita perlu menguasai beberapa skill yang dibutuhkan di masa depan (future skill) yang disebut digital capability. Kita semua perlu menemukan future skill dan menguasainya sehingga dapat beradaptasi di era digital. Find your own digital capability!',
    moderator: [],
    moderatorTitle: [],
    speaker: ['Irfan A Tachrir'],
    speakerTitle: ['Director of HCM at Telkomsel'],
    classImg: require('../assets/images/class1.png'),
    cta: 'Time: TBA',
    horizontal: true
  },
];
